apiVersion: v1
kind: Service
metadata:
  name: champ-web-svc
  namespace: champ-mini-project
spec:
  type: NodePort
  selector:
    app: champ-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

